### ISSUE TITLE
Extra boxes outside the windows

### ISSUE THREAD

**Issue by samchugit** [doncsugar/Genome-Spectrum#1]
![Screenshot_20201221_111307](https://user-images.githubusercontent.com/27361279/102735577-d21cae00-437d-11eb-9488-8b96de35a5b1.png)

Hi @doncsugar , I use your theme on my kde plasme 5.20.4 on Manjaro linux, and it show up extra transparent boxes outside the windows. You can notice them when the background is dark. Is it a bug or not compatible with my kde version.
Appreciate your work.

**Comment by doncsugar** [comment]
Hello Sam,

Thank you for emailing me. I tried Spectrum Light and Spectrum Dark on a
Manjaro Live USB.

The version is 20.2, Nibia.
KDE Plasma version is 5.20.4. KDE Frameworks is 5.76.0.
Qt is 5.15.2.

It appeared to be working fine and has the right margins.

It seems to be a bug. When I was making the Window Decoration theme, I
would encounter problems like what you are experiencing. It happens when
kde thinks the margin is one value, but the theme is changed to another,
afterwards. Do you have this problem with other Window Decoration themes?

After using Manjaro for a little bit, I think it may not be updated like
KDE Neon is. The only way I fixed the problem you are having on my main
system was by either restarting many times or making a new theme (with a
new name and everything, but same .svgs). Can you tell me if it looks the
same when you install the theme on a Manjaro Live USB?

thanks,


doncsugar
