### ISSUE TITLE
LibreOffice Options dialog box

### ISSUE THREAD

**Issue by Sadi58** [doncsugar/Genome-Spectrum#4]
I use Kvantum GenomeLight theme with Genome Light color-scheme, and I see a near perfect result in LibreOffice which usually creates problems for themers.
So far I've seen only two minor issues in the way of ultimate perfection:
- The lines in the tree of categories in the left box are too light 
-  Input field borders in the User Data tab are either missing or have the same color as the background.
![image](https://user-images.githubusercontent.com/6375934/136815321-7aea4250-8352-4d64-b6aa-e8c9a73daf15.png)

**Comment by doncsugar** [comment]
> I see a near perfect result in LibreOffice which usually creates problems for themers.

In the words of the maker of Kvantum, Breeze was designed to hide the hodgepodge of styles. You can see read about why themers struggle with it [here](https://github.com/tsujan/Kvantum/blob/master/Kvantum/doc/Theme-Making.pdf), under "A word about QML/Qt Quick." In any case, KDE plans to eventually make a new theme engine and drop Kvantum altogether.

> The lines in the tree of categories in the left box are too light

When I tried reproduce this, I don't even see branching lines. Libreoffice kf5 v6.4.7.2. Do the lines look right in other apps? To be clear, Spectrum doesn't really define colors, so it should be inherited from your color scheme.

> Input field borders in the User Data tab are either missing or have the same color as the background.

I think I have seen this one before in Lightly's bugs. I believe it is due to the thickness of the frame of the input fields. Which themes do you use that do not have this problem?

**Comment by Sadi58** [comment]
Default theme Breeze supports LibreOffice very well and has got this right, too.
It seems an item here is defined with white background.
 
![image](https://user-images.githubusercontent.com/6375934/136973187-f191a2be-27bd-4104-9eda-38c48e41693a.png)

**Comment by doncsugar** [comment]
Sorry for not being clear, the default Breeze theme cannot be compared to Kvantum. They work in different ways. I meant which Kvantum themes worked with it?

**Comment by Sadi58** [comment]
I tried several Kvantum themes that seem promising (e.g. KvAdapta, KvArc, KvAmbiance, KvOxygen, KvYaru...) but it's all the same. Maybe it's something to do with Kvantum and we can close this then?

**Comment by doncsugar** [comment]
You can present the issue in Kvantum.
