### ISSUE TITLE
Unreadable tooltips in GenomeLight

### ISSUE THREAD

**Issue by Vistaus** [doncsugar/Genome-Spectrum#6]
GenomeLight is a fantastic theme, thanks for making it! The only issue I have is that tooltips are unreadable. Could you please fix that? 🙂

**Comment by doncsugar** [comment]
Thanks!

I need more information, but my best guess is that the opacity is too low. You can change it with the script included in the theme. Check the description here: https://www.pling.com/p/1449495/

If that doesn't help, can you provide a screenshot with the tooltips?

Also, can you point me to the store page/download of the theme you are using?

**Comment by Vistaus** [comment]
Thanks for your suggestions! I installed GenomeLight from the latest git master.

Edit: sorry, my bad. I totally forgot to mention that my issue is with the Kvantum theme, not the Plasma theme.

**Comment by doncsugar** [comment]
No problem, I think your issue is tied to your Color Scheme. Try a different Color Scheme and see if that helps. If not, check the color for `Tooltip Text`. On a scheme I tried, it was really light for some reason:
![image](https://github.com/doncsugar/Genome-Spectrum/assets/46570709/73f3dc08-770a-4b9b-9d5d-bc1b82af9b6a)
Setting it to something close to Black should fix it.

**Comment by Vistaus** [comment]
You were right, it was the color scheme! Thank you for your help! 🙂
